- name: Configure build
        shell: powershell
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          New-Item -Force -ItemType Directory -Path build | Out-Null
          cd build
          
          # Caminhos absolutos apontando para a estrutura correta de 32 bits
          $ssl_base = "$env:OPENSSL_ROOT_DIR\openssl-1.1"
          $ssl_root = "$ssl_base\x86"
          $ssl_include = "$ssl_base\include"
          
          cmake -S ..\input-leap `
            -G "Visual Studio 17 2022" `
            -A Win32 `
            -D CMAKE_BUILD_TYPE=Release `
            -D QT_DEFAULT_MAJOR_VERSION=5 `
            -D INPUTLEAP_VERSION_DESC=release `
            -D INPUTLEAP_BUILD_GULRAK_FILESYSTEM=1 `
            -D DNSSD_LIB="$env:BONJOUR_SDK_HOME\Lib\Win32\dnssd.lib" `
            -D OPENSSL_ROOT_DIR="$ssl_root" `
            -D OPENSSL_INCLUDE_DIR="$ssl_include" `
            -D OPENSSL_CRYPTO_LIBRARY="$ssl_root\lib\libcrypto.lib" `
            -D OPENSSL_SSL_LIBRARY="$ssl_root\lib\libssl.lib" `
            -D CMAKE_INSTALL_PREFIX=input-leap-install
        env:
          BONJOUR_SDK_HOME: ${{ steps.bonjour.outputs.path }}
          OPENSSL_ROOT_DIR: ${{ steps.openssl.outputs.path }}
